export const dummy = [
    {
        _id: "a4dfad5fa4sf5dsf56ds4f",
        name: "Santo",
        area: "DHaka",
        address: "DHaka",
        phone: "DHaka",
        items: "DHaka",
    },
    {
        _id: "a4dfad5fa4sf5dsf56ds4f",
        name: "Santo",
        area: "DHaka",
        address: "DHaka",
        phone: "DHaka",
        items: "DHaka",
    },
    {
        _id: "a4dfad5fa4sf5dsf56ds4f",
        name: "Santo",
        area: "DHaka",
        address: "DHaka",
        phone: "DHaka",
        items: "DHaka",
    },
    {
        _id: "a4dfad5fa4sf5dsf56ds4f",
        name: "Santo",
        area: "DHaka",
        address: "DHaka",
        phone: "DHaka",
        items: "DHaka",
    },
    {
        _id: "a4dfad5fa4sf5dsf56ds4f",
        name: "Santo",
        area: "DHaka",
        address: "DHaka",
        phone: "DHaka",
        items: "DHaka",
    },
    {
        _id: "a4dfad5fa4sf5dsf56ds4f",
        name: "Santo",
        area: "DHaka",
        address: "DHaka",
        phone: "DHaka",
        items: "DHaka",
    },
]